package pl.edu.agh.iosr.realestatebroker.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.5
 * 2015-05-13T11:25:36.722+02:00
 * Generated source version: 3.0.5
 * 
 */
@WebService(targetNamespace = "http://iosr.agh.edu.pl/realestatebroker/webservice", name = "AddEstateInfoPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AddEstateInfoPortType {

    @WebResult(name = "estateInfoResponse", targetNamespace = "http://iosr.agh.edu.pl/realestatebroker/webservice", partName = "out")
    @WebMethod(operationName = "AddEstateInfo")
    public EstateInfoResponse addEstateInfo(
            @WebParam(partName = "in", name = "estateInfo", targetNamespace = "http://iosr.agh.edu.pl/realestatebroker/webservice")
            EstateInfo in
    );
}
